CREATE DATABASE IF NOT EXISTS OnlyFood CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE OnlyFood;

CREATE TABLE IF NOT EXISTS role (
  id_role INT AUTO_INCREMENT PRIMARY KEY,
  description VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  lastname VARCHAR(100) NOT NULL,
  id_role INT NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_user_role FOREIGN KEY (id_role) REFERENCES role(id_role)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS user_profile (
  user_id INT PRIMARY KEY,
  bio TEXT NULL,
  location VARCHAR(255) NULL,
  avatar_url VARCHAR(255) NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_profile_user FOREIGN KEY (user_id) REFERENCES user(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  content TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_posts_user FOREIGN KEY (user_id) REFERENCES user(id)
    ON DELETE CASCADE
) ENGINE=InnoDB;

INSERT INTO role (description)
SELECT 'vendor' WHERE NOT EXISTS (SELECT 1 FROM role WHERE description='vendor');
INSERT INTO role (description)
SELECT 'user' WHERE NOT EXISTS (SELECT 1 FROM role WHERE description='user');

ALTER TABLE catalog_item
ADD COLUMN image_url VARCHAR(255) DEFAULT NULL AFTER price,
ADD COLUMN vendor_id INT NULL AFTER image_url,
ADD CONSTRAINT fk_catalog_user FOREIGN KEY (vendor_id)
REFERENCES user(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

ALTER TABLE catalog_item
MODIFY vendor_id INT NOT NULL,
ADD CONSTRAINT fk_catalog_user FOREIGN KEY (vendor_id)
REFERENCES user(id)
ON DELETE CASCADE
ON UPDATE CASCADE;

